Numerous touch-ups to install scripts.

diff --git a/install/install-1st b/install/install-1st
--- a/install/install-1st
+++ b/install/install-1st
@@ -2,67 +2,94 @@
 
     if [[ $EUID -ne 0 ]]
     then
-		echo "$0 requires elevated privileges."
+		echo "$0 must be run as root."
 		sudo -H $0 $*
-		exit;
+		exit $?
 	fi
 
-# Create miners' user account
-MINERS_USER=${1:-albokiadt}
+# Grab the rig-tag
 [ -z "$HOSTNAME" ] && HOSTNAME=$(cat /etc/hostname)
 r_tag=$(echo $HOSTNAME|sed 's/rig-//')
-RIG_TAG=${2:-$r_tag}
-echo MINERS_USER=$MINERS_USER RIG_TAG=$RIG_TAG
+RIG_TAG=${1:-$r_tag}
+
+# Create miners' user account
+MINERS_USER=$2
+if [ -z "$MINERS_USER" ]; then
+  echo -n 'MINERS_USER account: '
+  read MINERS_USER
+  echo
+fi
+MINERS_PSW=$3
+while [ -z "$MINERS_PSW" ]; do
+  echo -n "$MINERS_USER password: "
+  read -s MINERS_PSW_FIRST
+  echo
+  echo -n "$MINERS_USER password, again: "
+  read -s MINERS_PSW_AGAIN
+  echo
+  if [ "$MINERS_PSW_AGAIN" = "$MINERS_PSW_FIRST" ]; then
+    MINERS_PSW=$MINERS_PSW_FIRST
+    break
+  else
+    echo "Passwords do not match."
+  fi
+done
+MINING_ROOT=${MINING_ROOT:-/opt/mining}
+
+usermod -a -G sudo -G staff -G root $MINERS_USER
+
+cat  > /etc/sudoers.d/miners << ETC_SUDOERS
+Defaults env_keep+="DISPLAY XAUTHORITY"
+$MINERS_USER ALL=(ALL) NOPASSWD: ALL
+ETC_SUDOERS
+chmod 0440 /etc/sudoers.d/miners
+
+[ ! -d /home/$MINERS_USER/.ssh ]&& mkdir /home/$MINERS_USER/.ssh && chmod 0700 /home/$MINERS_USER/.ssh
+echo $MINERS_PSW > /home/$MINERS_USER/.ssh/miners_user.psw
+chown $MINERS_USER:$MINERS_USER /home/$MINERS_USER/.ssh/miners_user.psw
+chmod 0600 /home/$MINERS_USER/.ssh/miners_user.psw
+
 
 ### Ref: https://www.cyberciti.biz/python-tutorials/linux-tutorial-install-ansible-configuration-management-and-it-automation-tool/
 apt-get -y install software-properties-common
-apt-add-repository ppa:ansible/ansible
+apt-add-repository -y ppa:ansible/ansible
 apt-get update
 apt-get -y install ansible
-sed -i.bak 's/#host_key_checking = False/host_key_checking = False/' /etc/ansible/ansible.cfg
 
 HOSTNAME=rig-$RIG_TAG
 hostname $HOSTNAME
 echo $HOSTNAME > /etc/hostname
+cat >> /etc/ansible/hosts << ANSIBLE_MINERS
 
-usermod -a -G sudo $MINERS_USER
+[miners]
+# Since this section is also read by miners.py for some of its configuration, this hosts
+#   file's format is somewhat limited, to "<IP_ADDR> hostname=<hostname> platform=<plat>"
+`hostname -I` hostname=$HOSTNAME platform=$PLATFORM
+
+ANSIBLE_MINERS
+sed -i.bak 's/#host_key_checking = False/host_key_checking = False/' /etc/ansible/ansible.cfg
+
+usermod -a -G sudo  $MINERS_USER
+usermod -a -G staff $MINERS_USER
 
 cat  >> /etc/sudoers << ETC_SUDOERS
 Defaults env_keep+="DISPLAY"
 $MINERS_USER ALL=(ALL) NOPASSWD: ALL
 ETC_SUDOERS
 
-# Make and configure some initial directories
-MINERS_FOLDERS='/opt/mining /opt/mining/install /var/mining /var/log/mining /var/run/miners /opt/Downloads /etc/mining /etc/ansible'
-mkdir -p $MINERS_FOLDERS 2>/dev/null
-chown -R ${MINERS_USER} $MINERS_FOLDERS
-# Make ~/.ssh folders in root and $MINERS_USER accounts
-mkdir -p ~/.ssh/config.d >/dev/null /home/${MINERS_USER}/.ssh/config.d >/dev/null
-chmod 0700 ~/.ssh/config.d /home/${MINERS_USER}/.ssh/config.d
-chown $MINERS_USER:$MINERS_USER /home/${MINERS_USER}/.ssh/config.d
-
-# Figure out if we have AMD graphic cards, Nvidia graphic cards, or both
-HAS_AMD=$(lspci | grep VGA | grep AMD    >/dev/null && echo AMD)
-HAS_NVI=$(lspci | grep VGA | grep NVIDIA >/dev/null && echo NVI)
-[ -n "$HAS_AMD" ] && PLATFORM=$HAS_AMD
-[ -n "$HAS_NVI" ] && PLATFORM=$HAS_NVI
-[ -n "$HAS_AMD" ] && [ -n "$HAS_NVI" ] && PLATFORM=BTH
-
 ### Great post at https://zxq9.com/archives/795
 cat >> /etc/environment << ETC_ENVIRONMENT
-CREATE_DATE_MINERS=`date --utc +%Y-%m-%dT%H-%M-%SZ`
 MINERS_USER=${MINERS_USER}
 RIG_TAG=$RIG_TAG
-PLATFORM=$PLATFORM
-LOG_DIR=/var/log/mining
-LOG_RAMDISK=/var/local/ramdisk
+MINING_ROOT=$MINING_ROOT
+XAUTHORITY=/home/$MINERS_USER/.Xauthority
+NO_AT_BRIDGE=1
+ANSIBLE_HOST_KEY_CHECKING=False
+INSTALL_DATE_MINERS=`date --utc +%Y-%m-%dT%H-%M-%SZ`
 NO_AT_BRIDGE=1
 ANSIBLE_HOST_KEY_CHECKING=False
 ETC_ENVIRONMENT
 source /etc/environment
-
-#echo '. /etc/profile' >> /root/.bashrc
-#echo '. /etc/profile' >> /home/${MINERS_USER}/.bashrc
 
 ### Turn off PCI ASPM (active state power management)
 ### Ref: https://askubuntu.com/questions/68372/how-do-i-add-pcie-aspm-force-to-my-boot-options
@@ -74,28 +101,18 @@ update-grub
 ### Ref: http://ask.xmodulo.com/disable-automatic-updates-ubuntu.html
 echo 'APT::Periodic::Unattended-Upgrade "0";' >> /etc/apt/apt.conf.d/10periodic 
 
-RAMDISK_SIZE=40M
-mkdir -p /var/local/ramdisk
-mount -t tmpfs -o size=${RAMDISK_SIZE} tmpfs /var/local/ramdisk
-chown ${MINERS_USER} /var/local/ramdisk         
-echo "none /var/local/ramdisk tmpfs nodev,nosuid,noexec,nodiratime,size=${RAMDISK_SIZE} 0 0" >> /etc/fstab
-## Test
-mount | grep /var/local/ramdisk
+# Make and configure some initial directories
+MINERS_FOLDERS='/opt/mining /var/mining /var/log/mining /var/run/miners /var/local/persist /opt/Downloads /etc/mining /etc/ansible'
+mkdir -p $MINERS_FOLDERS 2>/dev/null
+chown -R ${MINERS_USER} $MINERS_FOLDERS
+# Make ~/.ssh folders in root and $MINERS_USER accounts
+mkdir -p ~/.ssh/config.d >/dev/null /home/${MINERS_USER}/.ssh/config.d >/dev/null
+chmod 0700 ~/.ssh/config.d /home/${MINERS_USER}/.ssh/config.d
+chown -R $MINERS_USER:$MINERS_USER /home/${MINERS_USER}/.ssh
 
-apt-get -y update ; apt-get -y dist-upgrade
-apt-get -y autoremove ; apt-get -y autoclean
+echo "Basic OS, accounts, etc., for mining have been prepared."
+echo "A reboot is highly recommended at this point."
 
-apt-get -y install openssh-server git autoconf curl selinux-utils expect lrzip
-apt-get -y install libffi-dev libssl-dev python3-dev python3-pip
-
-pip install --upgrade pip
-pip install xlrd docopt requests jprops
-
-### TODO: does this do anything new? pip install ansible
-pip3 install bitshares
-
-# For PyCryptScraper
-apt-get -y install python-lxml
-pip install -U marshmallow --pre
-
-[ -n "$REBOOT_WHEN_NEEDED" ] && reboot || echo "A reboot is highly recommended at this point."
+echo "Hit ctrl-C to abort the reboot."
+sleep 10
+reboot
diff --git a/install/install-nvidia b/install/install-nvidia
--- a/install/install-nvidia
+++ b/install/install-nvidia
@@ -1,30 +1,52 @@
 #!/bin/bash
 
-if [[ $EUID -ne 0 ]]
-then
-    printf "%s\n" "This script must be run as root" 
-    exit 1
-fi
+  if [[ $EUID -ne 0 ]]
+  then
+		echo "$0 must be run as root."
+		sudo $0 $*
+		exit $?
+	fi
+
 pushd /opt
 
-NVIDIA_VERSION=${1:390.59}
+[ -n "$INSTALL_NVIDIA_DONE" ] && echo "Nvidia drivers and support already installed $INSTALL_NVIDIA_DONE." && echo "Do 'rm /etc/profile.d/nvidia.sh' to restart over from scratch." && exit 0
+
+################################################################################
+### Phase 0: Setup autostart ###################################################
+[ -f /etc/profile.d/nvidia.sh ] && source /etc/profile.d/nvidia.sh
+if [ -z "$INSTALL_NVIDIA" ]; then
+
+#cat > /etc/xdg/autostart/install-nvidia.desktop << NVIDIA_AUTOSTART
+#[Desktop Entry]
+#Type=Application
+#Name=Install Nvidia Drivers and Support
+#Exec=sudo /opt/mining/install/install-nvidia
+#NVIDIA_AUTOSTART
+
+NVIDIA_VERSION=${NVIDIA_VERSION:-390.59}
+# For GTX 750 TI -334.21 ?
 NVIDIA_VER_PTC=(${NVIDIA_VERSION//./ })
 NVIDIA_VER=${NVIDIA_VER_PTC[0]}
 NVIDIA_PATCH=${NVIDIA_VER_PTC[1]}
 
 cat >> /etc/profile.d/nvidia.sh << NVIDIA_SH
-export INSTALL_NVIDIA=`date --utc +%Y-%m-%dT%H-%M-%SZ`
-NVIDIA_VERSION=$NVIDIA_VERSION
+export NVIDIA_VERSION=$NVIDIA_VERSION
 export NVIDIA_VER=$NVIDIA_VER
 export NVIDIA_PATCH=$NVIDIA_PATCH
-export PATH=/usr/lib/nvidia-\$NVIDIA_VER/bin\${PATH:+:\$PATH}
-export LD_LIBRARY_PATH=/usr/lib/nvidia-\$NVIDIA_VER${LD_LIBRARY_PATH:+:\$LD_LIBRARY_PATH}
+export INSTALL_NVIDIA=`date --utc +%Y-%m-%dT%H-%M-%SZ`
 NVIDIA_SH
+
+fi
 source /etc/profile.d/nvidia.sh
 
+################################################################################
+### Phase 1: Remove Nouveau ####################################################
+if [ -z "$NVIDIA_NOUVEAU_REMOVED" ]; then
+  echo "Removing and disabling nouveau"
+  
 ### Ref: https://github.com/pearsonlab/pearsonlab.github.io/wiki/Things-to-know-when-installing-NVIDIA-drivers
-apt-get -y remove --purge nvidia* nouveau* && apt-get -y autoremove
-cat > /etc/modprobe.d/disable-nouveau.conf << EOT
+  apt-get -y remove --purge nvidia* nouveau* && apt-get -y autoremove
+  cat > /etc/modprobe.d/disable-nouveau.conf << DISABLE_NOUVEAU
 blacklist nouveau
 options nouveau modeset=0
 blacklist lbm-nouveau
@@ -36,39 +58,72 @@ blacklist nvidia-96-updates
 alias nvidia nvidia_current_updates
 alias nouveau off
 alias lbm-nouveau off
-EOT
-update-initramfs -u
+DISABLE_NOUVEAU
 
-cat > /etc/modprobe.d/nvidia-installer-disable-nouveau.conf << NOUVEAU_OFF
+  cat > /etc/modprobe.d/nvidia-installer-disable-nouveau.conf << BLACKLIST_NOUVEAU
 blacklist nouveau
 options nouveau modeset=0
-NOUVEAU_OFF
+BLACKLIST_NOUVEAU
 
-[ -n "$REBOOT_WHEN_NEEDED" ] && reboot || source /etc/profile.d/nvidia.sh
+### TODO: Why update-initramfs if 'remove --purge' didn't do anything?
+###    0 upgraded, 0 newly installed, 0 to remove and 156 not upgraded.
+###    update-initramfs: Generating /boot/initrd.img-4.13.0-36-generic
+  update-initramfs -u
 
-cd /opt/Downloads/
-wget https://us.download.nvidia.com/XFree86/Linux-x86_64/${NVIDIA_VER}.${NVIDIA_PATCH}/NVIDIA-Linux-x86_64-${NVIDIA_VER}.${NVIDIA_PATCH}.run
-### Question: When will we ever need X server?
-### Answer: nvidia-settings is too stupid to talk directly to its own GPUs and has to use X-server to do that for it.
-service lightdm stop
-sh NVIDIA-Linux-x86_64-${NVIDIA_VER}.${NVIDIA_PATCH}.run
-service lightdm start
-### See /usr/share/doc/NVIDIA_GLX-1.0/README.txt
+  echo "NVIDIA_NOUVEAU_REMOVED="`date --utc +%Y-%m-%dT%H-%M-%SZ` >> /etc/profile.d/nvidia.sh
+  echo "Nouveau has been removed and disabled."
+  echo "After this reboot, install-nvidia will proceed with installing Nvidia drivers."
 
-## gpustat works only for Nvidia GPUs
-pip install gpustat
-gpustat --no-color --show-cmd --show-power --json
+  echo "Hit ctrl-C to abort the reboot."
+  sleep 10
+  reboot
 
-### TEST
-cat /proc/driver/nvidia/version
-lsmod | grep nvidia
-nvidia-smi -L
-lspci|grep VGA
-
-[ -n "$VERBOSE" ] && nvidia-smi -a 
+fi
 
 
-cat >> /etc/profile.d/nvidia.sh << NVIDIA_SH
+################################################################################
+### Phase 2: Install Nvidia drivers ############################################
+################################################################################
+if [ -z "$NVIDIA_DRIVERS_INSTALLED" ]; then
+  cd /opt/Downloads/
+  [ -f NVIDIA-Linux-x86_64-${NVIDIA_VER}.${NVIDIA_PATCH}.run ] && rm NVIDIA-Linux-x86_64-${NVIDIA_VER}.${NVIDIA_PATCH}.run
+  wget https://us.download.nvidia.com/XFree86/Linux-x86_64/${NVIDIA_VER}.${NVIDIA_PATCH}/NVIDIA-Linux-x86_64-${NVIDIA_VER}.${NVIDIA_PATCH}.run
+  [ ! -f NVIDIA-Linux-x86_64-${NVIDIA_VER}.${NVIDIA_PATCH}.run ] && echo "Nvidia Drivers download failed!" && exit 1
+  ### Question: When will we ever need X server?
+  ### Answer: nvidia-settings is too stupid to talk directly to its own GPUs and has to use X-server to do that for it.
+  service lightdm stop
+  sh NVIDIA-Linux-x86_64-${NVIDIA_VER}.${NVIDIA_PATCH}.run --no-questions --disable-nouveau --ui=none --run-nvidia-xconfig
+  NVIDIA_RC=$?
+  rm NVIDIA-Linux-x86_64-${NVIDIA_VER}.${NVIDIA_PATCH}.run
+  service lightdm start
+  ### See /usr/share/doc/NVIDIA_GLX-1.0/README.txt
+
+  if [ $NVIDIA_RC != 0 ]; then
+    echo "FAIL: Execution of NVIDIA-Linux-x86_64-${NVIDIA_VER}.${NVIDIA_PATCH}.run RC=$NVIDIA_RC"
+    exit $NVIDIA_RC
+  fi
+  ## TODO: grep /var/log/nvidia-installer.log to determine if any NVIDIA.run failed.
+
+  cat >> /etc/profile.d/nvidia.sh << NVIDIA_DRIVERS_INSTALLED
+export PATH=/usr/lib/nvidia-\$NVIDIA_VER/bin\${PATH:+:\$PATH}
+export LD_LIBRARY_PATH=/usr/lib/nvidia-\$NVIDIA_VER${LD_LIBRARY_PATH:+:\$LD_LIBRARY_PATH}
+export NVIDIA_DRIVERS_INSTALLED=`date --utc +%Y-%m-%dT%H-%M-%SZ`
+NVIDIA_DRIVERS_INSTALLED
+
+  pip install gpustat
+
+  cat >> /etc/profile.d/nvidia.sh << NVIDIA_SH
 export INSTALL_NVIDIA_DONE=`date --utc +%Y-%m-%dT%H-%M-%SZ`
 NVIDIA_SH
-chmod 0754 /etc/profile.d/nvidia.sh
+  chmod 0754 /etc/profile.d/nvidia.sh
+
+  rm -f /etc/xdg/autostart/install-nvidia.desktop
+
+  echo "Nvidia drivers have been installed."
+  echo "After this reboot, install-nvidia will be complete."
+
+  echo "Hit ctrl-C to abort the reboot."
+  sleep 10
+  reboot
+
+fi
